### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by Klumbumbus** [osmlab/josm-tofix-plugin#107]
(from https://forum.openstreetmap.org/viewtopic.php?id=61559) 

In JOSM:

`API did not response! http://localhost:3000`

https://osmlab.github.io/to-fix/#/ gives

`NetworkError when attempting to fetch resource.`

**Comment by Rub21** [comment]
@Klumbumbus we have been working on setting up new backend instance for to-fix, so far is still not available!! if that is causing problems, we could disable the plugin, for a while?

**Comment by Klumbumbus** [comment]
So far I think it doesn't cause technical problems, only confused users ;) So if the new backend will be up soon you don't need to disable the plugin. If it will take longer then it might be better to disable it meanwhile.

**Comment by Rub21** [comment]
We've updated the plugin according to the new backend plugin: https://github.com/osmlab/to-fix-backend
