### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by stoecker** [osmlab/josm-tofix-plugin#108]
Build fails:

     [echo] compiling sources for /home/stoecker/sources/josm/dist/tofix.jar ...
    [javac] Compiling 33 source files to /home/stoecker/sources/josm/plugins/tofix/build
    [javac] /home/stoecker/sources/josm/plugins/tofix/src/org/openstreetmap/josm/plugins/tofix/TofixDialog.java:409: error: cannot find symbol
    [javac]             mainAccessToTask.setTask_isAllItemsLoad(listTaskBean.getTasks().get(cb.getSelectedIndex() - 1).getIsAllItemsLoad());
    [javac]                                                                                                           ^
    [javac]   symbol:   method getIsAllItemsLoad()
    [javac]   location: class TaskBean
    [javac] /home/stoecker/sources/josm/plugins/tofix/src/org/openstreetmap/josm/plugins/tofix/TofixDialog.java:410: error: cannot find symbol
    [javac]             mainAccessToTask.setTask_iduser(listTaskBean.getTasks().get(cb.getSelectedIndex() - 1).getIduser());
    [javac]                                                                                                   ^
    [javac]   symbol:   method getIduser()
    [javac]   location: class TaskBean
    [javac] /home/stoecker/sources/josm/plugins/tofix/src/org/openstreetmap/josm/plugins/tofix/TofixDialog.java:419: error: cannot find symbol
    [javac]             mainAccessToTask.setTask_type(listTaskBean.getTasks().get(cb.getSelectedIndex() - 1).getType());
    [javac]                                                                                                 ^
    [javac]   symbol:   method getType()
    [javac]   location: class TaskBean

**Comment by Rub21** [comment]
We updated according to the new tofix backend https://github.com/osmlab/to-fix-backend
