### ISSUE TITLE
add to PluginsSource

### ISSUE THREAD

**Issue by Klumbumbus** [osmlab/josm-tofix-plugin#110]
Is there a reason the plugin is not listed at https://josm.openstreetmap.de/wiki/PluginsSource? It can't be installed from within JOSM like shown in https://cloud.githubusercontent.com/assets/1152236/10457988/417882b4-718e-11e5-94b5-6ecf4a30eb43.gif

**Comment by don-vip** [comment]
Probably nobody noticed.

**Comment by don-vip** [comment]
This plugin depends on GeoJson plugin and so must be updated after changes from https://github.com/JOSM/geojson/issues/16

**Comment by don-vip** [comment]
Done
