### ISSUE TITLE
AddOn Installation

### ISSUE THREAD

**Issue by BigBen2003** [osmlab/josm-tofix-plugin#111]
Ich kann leider nur Deutsch, kein Englisch.

Das AddOn kann nicht wie in den Screenshots dargestellt installiert werden, da es nicht in der Liste der verfügbaren AddOns enthalten ist.

Auch nach der Aktualisierung der Liste von vorhandener Erweiterungen" wird es nicht unter "tofix" aufgelistet. Daher kann es auch nicht installiert werden.

Als Quelle der Erweiterungen ist gesetzt: https://josm.openstreetmap.de/pluginicons%<?plugins=>

**Comment by Bibi56** [comment]
Same as add #110 .
Wie  #110, nun in Deutscher Sprache ;-)
