### ISSUE TITLE
JOSM wireframe and GPX issue

### ISSUE THREAD

**Issue by Andygol** [osmlab/josm-tofix-plugin#12]
When "tofix layer" is active JOSM wireframe mode is broken
![to-fix_wireframe_mode_issue](https://cloud.githubusercontent.com/assets/369696/8699734/592e5fce-2b10-11e5-91f2-5db546e86753.gif)

**Comment by Andygol** [comment]
the same with GPX 
![to-fix_gpx_track_issue](https://cloud.githubusercontent.com/assets/369696/8719203/7d33e5fe-2bb2-11e5-8753-0bbd89afbbf7.gif)

**Comment by samely** [comment]
I've already fixed Wireframe and GPX issues.

![wireframe](https://cloud.githubusercontent.com/assets/10425629/15658480/9b590098-2682-11e6-8cd2-26b945dbb511.gif)

**Comment by Andygol** [comment]
@samely 👍 Thank you for this improvement
