### ISSUE TITLE
Limiting the downloading area

### ISSUE THREAD

**Issue by geochetan** [osmlab/josm-tofix-plugin#13]
The downloading area need to set in limit, we don't need large area near to the issue. It takes long time to download. 

![tofix](https://cloud.githubusercontent.com/assets/6770741/8794064/bec8156a-2f9c-11e5-8a67-0dca2298e99e.gif)

**Comment by Rub21** [comment]
@chtnha : I've fixed this issue. adding custom download.  just move the slide to download a large areas or small areas. 

![image](https://cloud.githubusercontent.com/assets/1152236/8859319/239bc36e-3142-11e5-82a4-920176492275.png)

Tell to all in office.
