### ISSUE TITLE
Plugin crashes after task update

### ISSUE THREAD

**Issue by planemad** [osmlab/josm-tofix-plugin#16]
After uploading a new CSV to the [japan unconnected task](http://osmlab.github.io/to-fix/?error=unconnected_major#/task/unconnectedjapan) and trying to use the plugin, it crashed and had to be disabled.

**Comment by planemad** [comment]
@Rub21 the plugin crashed again today. Do we need to keep updating the plugin every time?

**Comment by Rub21** [comment]
@planemad , it was because I've changed the to-fix-backend server, I requested to get a domain  for to-fix-backend, I will try to fix this soon as possible.

**Comment by Rub21** [comment]
fixed!!
