### ISSUE TITLE
Automatically set changeset comment

### ISSUE THREAD

**Issue by planemad** [osmlab/josm-tofix-plugin#17]
This can be similar to how the tasking manager sets the changeset comment for a task.

> Adding missing road connections on motorable roads using #to-fix:unconnected_major

**Comment by Rub21** [comment]
@planemad, I have added the automatic comment.  :) 

![image](https://cloud.githubusercontent.com/assets/1152236/10349623/0f798be2-6d05-11e5-94e7-248b704b8273.png)
![image](https://cloud.githubusercontent.com/assets/1152236/10351563/c30cfc70-6d0f-11e5-8366-1f87c82e4913.png)
