### ISSUE TITLE
Call Upload Changes dialog, when pressing Fixed button

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#18]
From @Andygol comment:

> What would you want to improve in to-fix web and to-fix plugin?
> 
> Call Upload Changes dialog, when pressing Fixed button, to submit correction to OSM DB. After successfully sending data to the server - load the next task, otherwise suggest to click a Not an error button

This is a good idea to add in plugin.

**Comment by Rub21** [comment]
@Andygol , I've added the  functionality,   now after click the `fixed` it will call upload change dialog.

**Comment by Andygol** [comment]
@Rub21 it is amazing. I'll test it on Monday
