### ISSUE TITLE
Make a choice between Github and OSM SVN

### ISSUE THREAD

**Issue by don-vip** [osmlab/josm-tofix-plugin#21]
Hi,
I see this Github plugin just has been committed also to OSM SVN:
https://trac.openstreetmap.org/changeset/31614/subversion

This is not how it works, you cannot manage a plugin at two different places.

If you prefer Github, the plugin must not be committed to OSM SVN and the folder thus deleted.
If you prefer OSM SVN, you should delete this repository to make it clear it is hosted on SVN.

If you choose SVN, the structure will have to be cleaned (remove "josm" from plugin name, remove class files, git info, etc.)

**Comment by Rub21** [comment]
@don-vip , if I choose Github, Should I add tofix.jar in http://svn.openstreetmap.org/applications/editors/josm/dist/.? to appear in list of Plugins? 

Also I saw Mapillary plugin ,[ it is SVN and in Github for development.](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Mapillary#Development.) 

I have been thinking like this, use SVN for source code, and Github for Latest development version.

**Comment by don-vip** [comment]
Hi :)

Concerning Mapillary: Github is only a mirror. The main source tree is on SVN.

To appear in the list of plugins you have two choices:
1) add the jar in dist folder of OSM SVN
2) add manually an external link to [JOSM wiki](https://josm.openstreetmap.de/wiki/PluginsSource). You must update the page each time the URL changes. Difference: by default JOSM will mention "plugin obtained from an external source" for end-users.

This being said, 3 types of JOSM plugins exist:
1) Those hosted on official OSM SVN. Pros: nothing to do on the JOSM wiki page, you will benefit from official translations (maintained by us), we will update your code each time a public JOSM API changes and impacts your plugin, so you don't have to worry with that neiher. Cons: you must use SVN, you cannot use the fancy features of Github (notably PR), you cannot control who has a write access to your plugin (but there is no vandalism neither, don't worry)
2) Those hosted on unofficial Github repositories. Pros: you control everything and can use all features from Github. Cons: your plugin will not be translated at all by the community (your strings won't appear on JOSM Launchpad) so you must handle it yourself. You will be impacted everytime we change a public API. You must update the JOSM wiki page at each new version (generally, plugin authors use the "release" Github mechanism. Example: [kendzi3d](https://github.com/kendzi/kendzi3d)
3) Those hosted on official [JOSM Github repository](https://github.com/JOSM). I think this is the best solution for you. Pros: everything. Cons: nothing. Example: [areaselector](https://github.com/JOSM/JOSM-areaselector). You can use all Github features. We take care of translations and public API changes. The need to edit the wiki page is optional (depending if you use the Github releases or not). The plugin is considered as official. You are still able to manage permissions on your plugin.

If you choose the third option, you need to [transfer your repository to the JOSM organization](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization). We will create a team managing the plugin, you will be its leader. Instead of copying the source code to SVN, we will only create a link to Github, this allows us to manage translations.

In all cases, the source code must be located at a single place :)

**Comment by Rub21** [comment]
@don-vip : I agree with third option. could give me the next steps to fallow? furthermore  remember https://github.com/osmlab/ is a organization. 
Thanks for your help, I will wait your instruction to  transfer the plugin  under  https://github.com/JOSM

**Comment by don-vip** [comment]
@Rub21 it's a long time since I invited someone to transfer his repo. I have created a new team and set you team maintainer, is it enough for you to transfer the repository?

**Comment by Rub21** [comment]
@don-vip I did the transfer to https://github.com/JOSM/tofix-plugin. In other hand is there a way to transfer the .jar automatically http://svn.openstreetmap.org/applications/editors/josm/dist/ or how should i do it? 

## The next Action
- [ ] @rub21 Remove the tofix-plugin from SVN

**Comment by don-vip** [comment]
Thanks! I have created the data folder so the i18n job won't fail anymore. The .jar file must be committed manually each time you want to release a new version. The issue can be closed :)
