### ISSUE TITLE
Install plugin w/o restarting JOSM

### ISSUE THREAD

**Issue by Andygol** [osmlab/josm-tofix-plugin#24]
According tweet - https://twitter.com/shtosm/status/654684061139472385

@Rub21 can you add possibility install plugin without restarting JOSM?

**Comment by don-vip** [comment]
See https://lists.openstreetmap.org/pipermail/josm-dev/2015-February/007185.html for details

**Comment by Rub21** [comment]
@Andygol @don-vip  done!  Now we can install tofix  without restart
![screenshot from 2015-11-04 15 53 24](https://cloud.githubusercontent.com/assets/1152236/10951739/27f342ee-830d-11e5-8264-7aeabd61425f.png)

**Comment by don-vip** [comment]
Great! :)

**Comment by Andygol** [comment]
:+1: :rocket:
