### ISSUE TITLE
Bug in fix-upload: doesn't respect "Cancel"

### ISSUE THREAD

**Issue by bdiscoe** [osmlab/josm-tofix-plugin#25]
Overall, the plugin works great for me, but I encounter this often:
1. I make edits and press "Fixed", which triggers an upload.
2. The warning box comes up saying there are validation failures.  I press "Cancel" because I want to fix those before uploading.
3. The plugin doesn't realize the upload was cancelled, and goes ahead to load the next task.

**Comment by Rub21** [comment]
Thank you for your feedback , I've fixed this bug, just need update the to-fix plugin.
