### ISSUE TITLE
Replace gson dependency by integrated jsonp

### ISSUE THREAD

**Issue by don-vip** [osmlab/josm-tofix-plugin#26]
I see you're using gson as an included dependency for JSON processing.

There's no no need for it. JOSM includes [jsonp](https://jsonp.java.net) directly, so it should be used instead.

**Comment by Rub21** [comment]
@don-vip . Sound fine,

 I will update the plugin  using `jsonp`

**Comment by Rub21** [comment]
I replace gson with jsonp !
done here, close.
