### ISSUE TITLE
Acces to repository 

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#27]
@don-vip  

I have tried to do `push` in this repo. However it sent me this message. could check the permission ,

![image](https://cloud.githubusercontent.com/assets/1152236/10583958/621d4326-7655-11e5-9b29-6d5502f17d82.png)

**Comment by Rub21** [comment]
I would like add new other members to `tofix` team as well,  people who are going to help to improve the plugin. 

cc. @don-vip

**Comment by don-vip** [comment]
I forgot to set the team admin of the repository, it's fixed now.
