### ISSUE TITLE
Update tofix.jar file in SVN

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#28]
@don-vip : 

I've updated the `tofix.jar` file in SVN, commit `31650.`

![image](https://cloud.githubusercontent.com/assets/1152236/10584380/8f5e26be-7657-11e5-9844-a72d58d8cf35.png)

But the version plugin in JOSM does not update  `31631`

![image](https://cloud.githubusercontent.com/assets/1152236/10584388/9b5ebef6-7657-11e5-9436-f5f3d340e325.png)

How much time it will take in update? .

**Comment by don-vip** [comment]
It's a matter of minutes, the version has been updated into the plugin list:
https://josm.openstreetmap.de/plugin

I have checked myself the version looks OK (1445191555 because it's the Github revision number).

**Comment by Rub21** [comment]
@don-vip:
  i don't  understand fine,
-  Is necessary to update the the .jar file  in SVN?, in my every update?  or JOSM will take the source from GitHub and build the tofix.jar file.?

**Comment by don-vip** [comment]
You must update the jar file each time you want to release a new version. JOSM does only monitor the dist folder for new jar files, it doesn't build plugins from sources.
