### ISSUE TITLE
Exception with ToFix plugin

### ISSUE THREAD

**Issue by karitotp** [osmlab/josm-tofix-plugin#29]
Since I started working with the task #91 everytime I upload my editing I get the following exception TOFIX plugin

![tofix](https://cloud.githubusercontent.com/assets/11504548/10695550/d573b794-7969-11e5-80bc-b26b63999618.png)

I updated the plugin but the problem continues.

@Rub21

**Comment by Rub21** [comment]
Thank you for your feedback , I've  fixed this error, just you need update the to-fix plugin.
