### ISSUE TITLE
Make Tofix-plugin faster

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#33]
some suggestions from my site: 
- Hide the upload dialog and upload the data in background
- Hide the download dialog and download the data in background.
- Use threads fro previous process  

thoughts? 

cc.@Andygol @planemad   @samely  @aarthykc @lxbarth @aaronlidman

**Comment by samely** [comment]
It's not a big deal, but a little disgusting to have lots of accumulated layers, especially when you want to manipulate imagery layers, so you may also delete the layer.

**Comment by Rub21** [comment]
>  you may also delete the layer.
> https://github.com/JOSM/tofix-plugin/issues/34

**Comment by Rub21** [comment]
Close!
