### ISSUE TITLE
Observaciones - tofix-plugin

### ISSUE THREAD

**Issue by ediyes** [osmlab/josm-tofix-plugin#4]
@Rub21 es posible ampliar el tamaño de descarga, exactamente con la herramienta del Tiger delta, debido a que no te descarga todo el error y tienes que volver a descargar para ampliar y son segundos que pierdes tiempo.

por ejemplo:
![ruben2](https://cloud.githubusercontent.com/assets/5991158/7971063/d547534c-0a07-11e5-8b95-75e54213df7d.PNG)

Lo de más esta bien, ayuda a hacer mas rápido el trabajo.

**Comment by Rub21** [comment]
@ediyes  gracias por al observacion, ya he implementado esta funcionalidad.
![image](https://cloud.githubusercontent.com/assets/1152236/9823073/b5b561a6-5889-11e5-984f-bec8246c96a0.png)
