### ISSUE TITLE
ToFix  - Excepción Inesperada

### ISSUE THREAD

**Issue by ridixcr** [osmlab/josm-tofix-plugin#42]
La excepción ocurre cuando se intenta dar clic derecho sobre la capa de ToFix para realizar cualquier tipo de  operación y no se despliega el menú.
![captura de pantalla de 2016-05-06 16-21-38](https://cloud.githubusercontent.com/assets/1646072/15086740/6de47008-13a8-11e6-8987-a4520e6ce44a.png)
Aparece la siguiente ventana, cuando se intenta cerra o hacer clic en un botón de la ventana este  muestra otra nueva ventana
![captura de pantalla de 2016-05-06 16-21-49](https://cloud.githubusercontent.com/assets/1646072/15086973/7e4e82c4-13aa-11e6-850f-6f8658149904.png)
al intentar cerrarla se repiten las ventanas de excepción
![captura de pantalla de 2016-05-06 16-21-58](https://cloud.githubusercontent.com/assets/1646072/15086975/8531300a-13aa-11e6-9291-1919259eb0ea.png)
![captura de pantalla de 2016-05-06 16-22-10](https://cloud.githubusercontent.com/assets/1646072/15086982/9266c708-13aa-11e6-99a1-04c87e408032.png)
por mas que se le checa en la opción para que no vuelva a mostrar dicho mensaje, lo muestra insistentemente y la única manera de salir de dicho bucle es cerrando definitivamente el JOSM Editor
![captura de pantalla de 2016-05-06 16-41-50](https://cloud.githubusercontent.com/assets/1646072/15086984/97d5547a-13aa-11e6-9f42-419816a85275.png)
Este es la versión del ToFix que se esta utilizando.

@Rub21 !!!

**Comment by samely** [comment]
Realizamos las pruebas y no se repitió el error. En caso de volver a ocurrir, reabrir el ticket por favor.
 Cerrando.
