### ISSUE TITLE
Pressing "cancel" on Fixed: Upload causes all data to be lost

### ISSUE THREAD

**Issue by bdiscoe** [osmlab/josm-tofix-plugin#43]
I encountered this, trying to use the To-fix plugin (version 1462371975) on the task "Highway intersects water - major":
1. Make changes to fix the problem
2. Press "Fixed".
3. The validation dialog appears, telling you that there are validation problems.
4. Press "Cancel" to go back and fix them before uploading.

At this point, To-fix plugin _deleted_ all the work i had done, cleared the current layer, and took me to the next problem to fix.  I had actually done a lot more than just fix the problem, so I lost 20 minutes worth of mapping work!  This is a really, really bad bug.

**Comment by samely** [comment]
Hi @bdiscoe,
This bug has been solved. You can try it again.
Thanks for your feedback!

**Comment by samely** [comment]
When canceling validator dialog, there's no lost data anymore.
![validator](https://cloud.githubusercontent.com/assets/10425629/15548671/12856322-226f-11e6-81a4-a7a81463d3b8.gif)

cc. @Rub21  @bdiscoe

**Comment by bdiscoe** [comment]
Confirmed fixed, thanks!
