### ISSUE TITLE
Skipping more then 1 issue

### ISSUE THREAD

**Issue by Andygol** [osmlab/josm-tofix-plugin#5]
![josm_to_fix_skiping_task](https://cloud.githubusercontent.com/assets/369696/8162354/5dc2ba50-1385-11e5-80e3-195921fb2662.gif)
When `Skip` button is pressed, JOSM jump over one task, see picture above

**Comment by Rub21** [comment]
@Andygol , I fixed this error , for next version it would be release. 

Thanks, close here.
