### ISSUE TITLE
Error en windows 

### ISSUE THREAD

**Issue by piligab** [osmlab/josm-tofix-plugin#52]
Error en Windows!!, al trabajar en el osm usando el ToFix. Al momento de corregir el error y habiendo carreteras que faltan trazar, se realiza el trazado respectivo. Terminado esto se hace click en Fixed y aparece el error que se muestra a continuación.

![sin titulo3](https://cloud.githubusercontent.com/assets/19536044/15784133/c4c22c42-2976-11e6-9e37-6f29a730cd39.png)

Haciendo seguimiento en el cmd se muestra lo siguiente.

![sin titulo](https://cloud.githubusercontent.com/assets/19536044/15783913/b5992366-2975-11e6-86e7-e5befc8244ee.png)

![sin titulo2](https://cloud.githubusercontent.com/assets/19536044/15783950/eb19dd3c-2975-11e6-8f41-e1e15b3502c7.png)

@samely @Rub21

**Comment by samely** [comment]
Este error fue resuelto en las actualizaciones que se hicieron al to-fix plugin.
