### ISSUE TITLE
Report Bug en To-Fix

### ISSUE THREAD

**Issue by Yurasi** [osmlab/josm-tofix-plugin#54]
Este mensaje aparece por momentos cuando estoy subiendo un cambio en el To-Fix.

![captura de pantalla de 2016-06-08 16-52-39](https://cloud.githubusercontent.com/assets/12261974/15912374/7844b0f2-2d99-11e6-9041-4a83b1d317b5.png)

Y cuando hago clic en "Reportar Bug", aparece la siguiente imagen.
![captura de pantalla de 2016-06-08 16-46-32](https://cloud.githubusercontent.com/assets/12261974/15912286/f69c8444-2d98-11e6-8832-73e803cf4c8d.png)

@samely

**Comment by samely** [comment]
This has been already solved.
