### ISSUE TITLE
set up icon for to-fix layer

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#57]
cc. @samely

**Comment by samely** [comment]
:hammer:

**Comment by samely** [comment]
Done!
![image](https://cloud.githubusercontent.com/assets/10425629/16201981/676afc2a-36d9-11e6-9b3c-9dad16aa3328.png)

**Comment by Rub21** [comment]
@samely , I mean this layer , currently we are using a default icon, we have to change it by this https://github.com/JOSM/tofix-plugin/blob/91fa100ff75f2c45979d43afb2db2561d6c6ad7f/images/icontofix.png

![image](https://cloud.githubusercontent.com/assets/1152236/16216395/0c9b4276-3730-11e6-89a4-ca3c3a14ab39.png)

**Comment by samely** [comment]
Done!
![image](https://cloud.githubusercontent.com/assets/10425629/16248675/2dd498e2-37d6-11e6-89f0-94a63f30c595.png)

**Comment by Rub21** [comment]
nice!
