### ISSUE TITLE
The same set of buttons as in the web interface and some suggestion 

### ISSUE THREAD

**Issue by Andygol** [osmlab/josm-tofix-plugin#6]
![image](https://cloud.githubusercontent.com/assets/369696/8162963/12623456-1389-11e5-907e-cf6c3152b2be.png)
@Rub21 
- [x] could you make the same set of buttons in the plugin?
- [x] I have suggestion to add settings to toggle mode of the `Fixed` button. When state is `on`, `Upload` dialog will be opened and after submitting changeset to the OSM server will be loaded next issue; `off` - behavior the same as for now
- [x] One more - add option which enabled/disabled automtical removing of the previous data layer after clicking on `Skip`, `Fixed` and `Not an error` buttons

**Comment by Rub21** [comment]
@Andygol 

> could you make the same set of buttons in the plugin?

I talked this with Aaron, and we agree to remove `edit` button, tofix plugin  should work Automatically download after clicked in  Skip/Fixed"

And about `No and error` button it will be release for next version,

> I have suggestion to add settings to toggle mode of the Fixed button. When state is on, Upload dialog will be opened and after submitting changeset to the OSM server will be loaded next issue; off - behavior the same as for now

I am thinking on how to do this, it could  be much better  to  fetch data faster than now. 

> One more - add option which enabled/disabled automtical removing of the previous data layer after clicking on Skip, Fixed and Not an error buttons

This is a good idea , I will try to implement  this on plugin

**Comment by Andygol** [comment]
1st item completed :tada: https://github.com/JOSM/tofix-plugin/issues/6#issue-88460009
![image](https://cloud.githubusercontent.com/assets/369696/10560240/73d323f4-750d-11e5-8f1f-6607e19f3b2c.png)

**Comment by samely** [comment]
@Andygol  @Rub21 
I added the auto-deleting option and also another option to [desactivate the plugin](https://github.com/JOSM/tofix-plugin/issues/44)

![image](https://cloud.githubusercontent.com/assets/10425629/15435165/4c87e3a8-1e80-11e6-8fb3-1c06987d9d8c.png)

**Comment by samely** [comment]
Since all is done, closing here.

**Comment by Andygol** [comment]
Cool work @samely 👍 🎉 🎉
