### ISSUE TITLE
Fix the big bbox issue

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#66]
There are feedbacks from community about the large bbox using to-fix.

We should try to avoid the the big bbox when are a using to-fix task. we  have some tentative issues why this happens, but we are not sure the exact reason.
- Internet problem?
- To-fix-plugin problem?
- Use in parallel JOSM windows?

We will follow on this ticket to figure out those issues and resolve them. 
@planemad  @samely @jinalfoflia @oini @srividyacb

**Comment by samely** [comment]
I worked on this issue. I updated the plugin that avoids you to upload data the places are too far. 
We just need to upload the plugin.
![anim](https://cloud.githubusercontent.com/assets/10425629/17379196/deafe596-5986-11e6-8e70-1c329777601b.gif)

**Comment by samely** [comment]
This is already merged.
