### ISSUE TITLE
Plugin freezes JOSM when backend does not respond

### ISSUE THREAD

**Issue by Andygol** [osmlab/josm-tofix-plugin#7]
@Rub21 
Connected with https://github.com/osmlab/to-fix/issues/123

JOSM freezes for a long time (~10 min) and do not respond on any actions

After this time, I get such dialog (buttons: Cancel, No, Yes)
![image](https://cloud.githubusercontent.com/assets/369696/8281788/10b972e8-18f4-11e5-8cfb-c4085850bf0c.png)
How to treat in this situation?

**Comment by Rub21** [comment]
This was solved in actual version. 
close!
