### ISSUE TITLE
Big bounding box

### ISSUE THREAD

**Issue by samely** [osmlab/josm-tofix-plugin#74]
There were many changesets with a big bounding box, specifically working with JOSM 11223 and Windows.

**Comment by ediyes** [comment]
I still have the problem of the big bounding box.

![image](https://cloud.githubusercontent.com/assets/5991158/21614740/b833a5ca-d1a8-11e6-9b59-f1069dd5ee9c.png)


 Any updates here @samely ?

**Comment by samely** [comment]
This bug has been [fixed](https://github.com/JOSM/tofix/pull/75).
