### ISSUE TITLE
Auto delete layer not working

### ISSUE THREAD

**Issue by abhisheksaikia** [osmlab/josm-tofix-plugin#76]
After every task in to-fix, the previous layer should automatically delete. But this is not happening and we are manually deleting the previous layer. Using the latest version of JOSM (11427)

cc @Rub21 @samely @krishnanammala

**Comment by abhisheksaikia** [comment]
Adding to this, the layers do get deleted automatically if you click on `Fixed` and it is uploaded, but not if you click on `Skip` and `Not an error`.

**Comment by samely** [comment]
Thanks for reporting this. [I've fixed](https://github.com/JOSM/tofix/pull/77) the autodelete action for buttons.
Remember that you can also configure the shortcuts for to-fix actions

![image](https://cloud.githubusercontent.com/assets/10425629/21856009/60ab18c8-d7ee-11e6-8c82-7b0c1fe78e9c.png)
