### ISSUE TITLE
Support for relation objets

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#82]
To-fix web has already support for relations, can we do the same thing for the plugin. 

![pasted_image_at_2017_02_15_09_26_pm](https://cloud.githubusercontent.com/assets/1152236/23032618/07c6f74c-f443-11e6-96b8-87da46d45851.png)
cc. @samely

**Comment by samely** [comment]
Amazing! :heart: will work on it!

**Comment by samely** [comment]
Done here!
