### ISSUE TITLE
summary of issues 

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#83]
https://josm.openstreetmap.de/ticket/13993#comment:10
https://josm.openstreetmap.de/ticket/14506#comment:1
https://josm.openstreetmap.de/ticket/14511#comment:1
https://josm.openstreetmap.de/ticket/14509#comment:1
https://josm.openstreetmap.de/ticket/14512#comment:1
https://josm.openstreetmap.de/ticket/13993#comment:22

cc. @samely

**Comment by samely** [comment]
@Rub21 I cannot replicate those scenarios, maybe it was fixed in the last update. So closing here until reply of my [comment](https://josm.openstreetmap.de/ticket/13993#comment:10)
