### ISSUE TITLE
calculate bbox to download

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#85]
Would be good if the plugin could download all the areas where the issues, so we would not have the need to download new more area.

![image](https://cloud.githubusercontent.com/assets/1152236/25239825/ce6c8a52-25b6-11e7-9559-ed64d55bf3d5.png)

**Comment by samely** [comment]
Done here!

![image](https://cloud.githubusercontent.com/assets/10425629/25296778/9bb0ee92-26af-11e7-9c7d-9d96c850d501.png)
*Conservation broken relation issue*
