### ISSUE TITLE
Select relation in JOSM

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#89]
When to-fix is getting relation data, the relations should be selected to easy visualizations and know which relations need to resolve. 
![image](https://user-images.githubusercontent.com/1152236/26933162-5efa7a1c-4c2b-11e7-9553-24c274602bdc.png)
cc. @samely

**Comment by samely** [comment]
I will work on it!

**Comment by samely** [comment]
I've already [fixed](https://github.com/JOSM/tofix/pull/90) this.
