### ISSUE TITLE
Upload on clicking fixed

### ISSUE THREAD

**Issue by planemad** [osmlab/josm-tofix-plugin#9]
Since we always upload data before clicking fixed, we can link the two actions.

**Suggested workflow**
- On clicking `Fixed`, the upload manager is triggered
- The changeset comment is auto populated `To-fix:<Task Name>` and source `<List of active raster imagery layers>`
- On successful upload, the plugin should mark the issue as fixed and move to the next issue

**Comment by Andygol** [comment]
@planemad does it the same as https://github.com/JOSM/tofix-plugin/issues/6?

**Comment by samely** [comment]
This was solved. 
Closing here
