### ISSUE TITLE
Customize the URL 

### ISSUE THREAD

**Issue by Rub21** [osmlab/josm-tofix-plugin#91]
cc. @samely

**Comment by samely** [comment]
Can you give more context @Rub21 I don't know what url :pray:

**Comment by Rub21** [comment]
https://github.com/JOSM/tofix/blob/master/src/org/openstreetmap/josm/plugins/tofix/util/Config.java#L5
podemos  hacer  que la URL del API  :point_up_2:  sea configurable,  por defecto esta bien que tenga esa url del API , pero  necesitamos que se puede cambiar la url del API.

**Comment by samely** [comment]
@Rub21 [done!](https://github.com/JOSM/tofix/pull/94)

![image](https://user-images.githubusercontent.com/10425629/27838702-fccecdd4-60b1-11e7-9182-8d5cb12e99a5.png)
