### ISSUE TITLE
To-fix not paused/stopped when the plugin window is closed

### ISSUE THREAD

**Issue by muzirian-zz** [osmlab/josm-tofix-plugin#93]
Was expecting the To-fix plugin to pause be inactive when the plugin window is closed in josm.
But shortcuts for To-fix plugin still works with the window closed.
 
Deleting/downloading layers if shortcuts are pressed accidentally.
@Rub21 @samely

**Comment by samely** [comment]
@muzirian this is the reason we have the **Activation** panel, you can enable/disable the plugin by clicking the checkbox.
![image](https://user-images.githubusercontent.com/10425629/27842308-986deaa6-60ce-11e7-89d0-2959ab3480da.png)

However I will  disable the plugin when closing the panel. Thanks for flagging this out :bowing_woman: 
I will let you know when ready so you can update the plugin.

**Comment by muzirian-zz** [comment]
oky thnx, will try tht

**Comment by Rub21** [comment]
No longer available for the old version of to-fix backend
