### ISSUE TITLE
Custom url gets reset when josm is restarted

### ISSUE THREAD

**Issue by muzirian-zz** [osmlab/josm-tofix-plugin#96]
Custom url added under activation tab in to-fix is reset to default when josm is restarted.
So have to uncheck the default url option and enter the url each time when josm is opened.

@Rub21 @samely

**Comment by muzirian-zz** [comment]
an option to save custom urls will be awesome 😄

**Comment by samely** [comment]
@muzirian Thanks for flagging this, just so you know I added this to my plate. I will comment here when done. :bowing_woman:

**Comment by muzirian-zz** [comment]
Thanks :) 🙇

**Comment by Rub21** [comment]
A new version was released !!
