### ISSUE TITLE
To-fix plugin in Josm not handling conflicts

### ISSUE THREAD

**Issue by kupendrayadav** [osmlab/josm-tofix-plugin#98]
To-fix plugin in the Josm is not handling the conflicts. 

- When we click the `fixed` button in the plugin, It shows the conflicts but it's skipping to another task by showing`unable to resolve conflicts` message.
- You can resolve conflicts only when you manually upload and then these conflicts can be resolved.

Also,

Can we get any warning message kind of thing when we accidentally press `skip` or `not an error` after making some changes to the task? Currently, when you make edits to task and accidentally press `skip` or `not an error` instead of `fixed`. Due to this, we are losing the edits that we made to the particular task.

@Rub21 @samely @abhisheksaikia

**Comment by Rub21** [comment]
A new version was released !!
